packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: set this to true or false
  sharp: set this to true or false

strictDepBuilds: false

onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
  - sharp
